### ISSUE TITLE
Getting errors when running emails.py

### ISSUE THREAD

**Issue by Chilly0z** [hendrikbgr/ProtonMail-Account-Creator#13]
Getting the following error. Using Windows 10 64 bit Python 3.7.6

```
Traceback (most recent call last):
  File "C:\Users\kmhs1\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\kmhs1\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\kmhs1\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "emails.py", line 92, in <module>
    driver = webdriver.Chrome(executable_path='/driver/chromedriver', chrome_options=options)
  File "C:\Users\kmhs1\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\kmhs1\AppData\Roaming\Python\Python37\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

**Comment by hendrikbgr** [comment]
you need to place the chromedriver file in the driver folder. and make sure to rename it to 'chromedriver'. You can download it here: https://chromedriver.chromium.org/downloads

**Comment by hendrikbgr** [comment]
I am closing the issue, I guess it got resolved(?)

**Comment by kolet** [comment]
@hendrikbgr  i will reopen this if u dont mind.

having the same issue, and i am using linux ubuntu.
i downloaded the latest chormin from here https://chromedriver.storage.googleapis.com/index.html?path=83.0.4103.39/  

i set the path to the binary file. from the unziped file.
error i get "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary"

i even ran the binary on "screen" on the backround.

> driver = webdriver.Chrome('/tmp/chromedriver')
or

> driver = webdriver.Chrome(executable_path='/root/ProtonMail-Account-Creator/chromedriver', chrome_options=options)

same issue. 

by the way its worth noticing its python3 that u are using :) 

anyhow , would be great if u could help us fixing it

**Comment by kolet** [comment]
for the test i also tried windows machine , win7 with python3 

error out 

> selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 83

or 

> selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 78

with a different version..

**Comment by hendrikbgr** [comment]
I will look into this today. I think the python module I used to crawl proxies does not work any longer and therefore the script wont work either. I will have to do some changes on that.

**Comment by kolet** [comment]
@hendrikbgr  the proxie crawler seems to work fine , as it does find and connect to the proxies  (i think)

**Comment by hendrikbgr** [comment]
so I had a look at it. You need to do a couple of things:
- Pull from master branch (pushed a small bug fix)
- Download the right chromedriver version for your system and chrome version installed
- create a folder called 'driver' in the main project folder
- place the chromedriver executable in that driver folder and make sure it's called 'chromedriver'

Also by the looks of it the proxy crawler does not really work any longer. The script will detect a working proxy but in reality that proxy is dead. So I will have to look into that and might have to replace the current script

**Comment by hendrikbgr** [comment]
I am also adding a feature where you can enter your own proxies into a text file. That should work better for now

**Comment by Chilly0z** [comment]
@hendrikbgr So as of right now, is there a way to prevent it from using the built in scraper and where do we put our personal proxies? Is there a format the proxies need to follow when being input?

**Comment by hendrikbgr** [comment]
I now added two new options to the script. The first is that you can run the script proxy less. The second is that you can resolve the captcha yourself and tell the script when its resolved. For that leave the verification email question empty and select verification by captcha. Then resolve the captcha and hit enter in the script window.

I will close this issue but if any further questions exist feel free to reopen.

**Comment by hendrikbgr** [comment]
> @hendrikbgr So as of right now, is there a way to prevent it from using the built in scraper and where do we put our personal proxies? Is there a format the proxies need to follow when being input?

proxy format for proxy file:
ip:port
ip:port
ip:port

etc...
