### ISSUE TITLE
website not loading

### ISSUE THREAD

**Issue by ppkantorski** [hendrikbgr/ProtonMail-Account-Creator#14]
It seems like the proxy might not be working properly?  When chrome opens, it is unable to load the website.

 - OS: macOS Catalina
 - Python Version 3.8
 - Chrome version 81.0.4044.138)

**Comment by ppkantorski** [comment]
ERR_TUNNEL_CONNECTION_FAILED

**Comment by hendrikbgr** [comment]
It might be that the proxy which is crawled is not working. Is this something which happens every time you start the script? Or does it occurs once in a while?

**Comment by ppkantorski** [comment]
it tries to connect a few times, then connects, but the web browser then says ERR_TUNNEL_CONNECTION_FAILED and webpages do not load.  One other thing, you might want to remove the emoji's from the script.  They aren't recognized within Python and cause errors.

**Comment by ppkantorski** [comment]
Issue has been resolved.  I had to change my computers DNS.  Chose 1.1.1.1 and 1.0.0.1, now it doesn't have that issue anymore

**Comment by ppkantorski** [comment]
ok weird. it worked then it stopped.  can't get it to work again

**Comment by hendrikbgr** [comment]
so it turns out the proxy crawler does not work any longer. Either that or the proxy checker doesn't work. I will add an option to run the script without proxy for now and then look into an alternative for the proxy crawler

**Comment by javamash** [comment]
Any ETA on that proxy-less option? I'll attempt it in a little bit but it would be a lifesaver.

**Comment by OhItsTom** [comment]
> so it turns out the proxy crawler does not work any longer. Either that or the proxy checker doesn't work. I will add an option to run the script without proxy for now and then look into an alternative for the proxy crawler

[55688:57708:0526/175540.887:ERROR:device_event_log_impl.cc(208)] [17:55:40.887] Bluetooth: bluetooth_adapter_winrt.cc:1060 Getting Default Adapter failed.

**Comment by hendrikbgr** [comment]
Yes I will be releasing a proxy less version soon.

**Comment by makiado** [comment]
I love you ! thats is possible to pre add the recovery email and them the script go all way so you just need to capta? 💯

**Comment by javamash** [comment]
Got it to work after a little bit of editing, but I run into the issue of getting locked to verify via SMS.

**Comment by hendrikbgr** [comment]
> I love you ! thats is possible to pre add the recovery email and them the script go all way so you just need to capta? 💯

I use 10min mail and similar email services to create email for verification. Recovery email is optional. Also problem with the captcha and no proxy is that they will force you to use sms as verification after a few tries. If you use proxies you can do the email verification which is the easiest. 

> Got it to work after a little bit of editing, but I run into the issue of getting locked to verify via SMS.

You will get blocked doing email or captcha verifications if you dont use proxies.

**Comment by hendrikbgr** [comment]
I now added two new options to the script. The first is that you can run the script proxy less. The second is that you can resolve the captcha yourself and tell the script when its resolved. For that leave the verification email question empty and select verification by captcha. Then resolve the captcha and hit enter in the script window.

I will close this issue but if any further questions exist feel free to reopen.
