### ISSUE TITLE
Captcha verification

### ISSUE THREAD

**Issue by Boffice** [hendrikbgr/ProtonMail-Account-Creator#15]
This is amazing script but email verification part is confusing, so basically you need more emails to create new emails , why not just use captcha and process can become automatic using services like 2captcha

**Comment by hendrikbgr** [comment]
you can use 10min mail or similar services to get those email addresses verified. And they block the option to use captcha after a few accounts. So email is the only consistent way of verifying.

**Comment by hendrikbgr** [comment]
I now added two new options to the script. The first is that you can run the script proxy less. The second is that you can resolve the captcha yourself and tell the script when its resolved. For that leave the verification email question empty and select verification by captcha. Then resolve the captcha and hit enter in the script window.

I will close this issue but if any further questions exists feel free to reopen.

**Comment by tmxd09887** [comment]
After registering several new accounts, protonmail will block the email address for a period of time, and must change the email domain name. How to solve this?
