### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lilcsz** [hendrikbgr/ProtonMail-Account-Creator#17]
ERROR:
/driver/chromedriver', chrome_options=options)
NameError: name 'options' is not defined

 - OS: Windows 10
 - Python 3.8.3

**Comment by lilcsz** [comment]
I have this error on: (1) - Crawl Free Proxies

**Comment by hendrikbgr** [comment]
this seems strange to me. Since 'options' is defined before it gets called. I will have to do some investigation

**Comment by igosad** [comment]
options = webdriver.ChromeOptions()
add this before the call

**Comment by lilcsz** [comment]
@igosad thanks
