### ISSUE TITLE
I can't use proxy

### ISSUE THREAD

**Issue by lilcsz** [hendrikbgr/ProtonMail-Account-Creator#18]
Can't use proxy

![image](https://user-images.githubusercontent.com/43272857/85320784-4f995b80-b4cc-11ea-8849-ed5d63fc77fe.png)

OS: Windows 10
Python 3.8.3

**Comment by hendrikbgr** [comment]
the proxy crawler is broken atm. I used some third party module which is out of date now. the only way to use a proxy is to set your own in the proxy file

**Comment by lilcsz** [comment]
I used my own proxy list

**Comment by hendrikbgr** [comment]
Looks like I will have to rewrite the proxy part of this script. Will tackle this as soon as I can

**Comment by hendrikbgr** [comment]
I tried the proxy crawling feature. It seems to be working now. So feel free to use that instead
