### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by millysecurity** [hendrikbgr/ProtonMail-Account-Creator#21]
When I do option 2 for loading proxies from file, it finds a working proxy and then errors out with the following message. 
  
![q32GEyz](https://user-images.githubusercontent.com/64474721/90465230-eead8e80-e0dc-11ea-8045-360e3bb1c3cd.png)
 
and when I instead tried using option 1 for the free proxy scraper, it threw this error..
  
![cmd_c4ZQ8OH1Us](https://user-images.githubusercontent.com/64474721/90465330-287e9500-e0dd-11ea-8e49-8cc47b828753.png)

**Comment by lilcsz** [comment]
add this to line 145

options = webdriver.ChromeOptions()

**Comment by karlhdenby** [comment]
> add this to line 145
> 
> options = webdriver.ChromeOptions()

whenever I do that the command won't load lol, I think I put it in the wrong spot can you be more specific?

**Comment by hendrikbgr** [comment]
This issue has been fixed with the latest update
