### ISSUE TITLE
Bot is stuck if nickname is already used

### ISSUE THREAD

**Issue by Itamai** [hendrikbgr/ProtonMail-Account-Creator#22]
Before trying to register send a get request to this api
https://mail.protonmail.com/api/users/available?Name=herethenickname
and if you dont get code 1000 in the response generate another name

Right now your bot is stuck if the nickname is already used

And a question.
Are you still working on this or going to work on this?
I can help you with this project

**Comment by hendrikbgr** [comment]
Hello, yes that's a great idea. I will make sure to add it soon. I am working on this project but not very often. I am currently working on multiple projects and this is not my highest priority

**Comment by hendrikbgr** [comment]
added your PR to the project 👍🏼
