### ISSUE TITLE
Working Slowly

### ISSUE THREAD

**Issue by FeelsBadMan1** [hendrikbgr/ProtonMail-Account-Creator#25]
I'm always frustrated when i want to create many mail accounts but need to write the whole setup for each new mail again.

I want that there is a option to enable loopmode and this will just ask the first time after running the script for the setup. after that it will automatically create new accounts if one is done and keeping the settings.

**Comment by hendrikbgr** [comment]
once the proxy is fully working again this will be the next feature

**Comment by hendrikbgr** [comment]
This will be possible with the next version
