### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by xiaoming140** [hendrikbgr/ProtonMail-Account-Creator#27]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'r
equirements.txt'

C:\Users\Administrator>
C:\Users\Administrator>

**Comment by xiaoming140** [comment]
and also

Traceback (most recent call last):
  File "F:\ProtonMail-Account-Creator-master\emails.py", line 14, in <module>
    from proxyscrape import create_collector
ModuleNotFoundError: No module named 'proxyscrape'

**Comment by ishan-rightapps** [comment]
@xiaoming140 You need to run this command in the same folder as the project. ```pip install -r requirements.txt``` installs the project dependencies.

**Comment by hendrikbgr** [comment]
if the requirements file does not work you can install the missing modules manually by doing something like: 'pip install proxyscrape'

**Comment by hendrikbgr** [comment]
fix in comment above
