### ISSUE TITLE
please define google Chrome driver Version 

### ISSUE THREAD

**Issue by traderpedroso** [hendrikbgr/ProtonMail-Account-Creator#31]
selenium.common.exceptions.NoSuchFrameException: Message: no such frame
  (Session info: chrome=89.0.4389.82)

i guess its some thing to do with the driver version

**Comment by hendrikbgr** [comment]
you need to have to either install a version of chrome that matches your chromedriver or download the matching chromedriver to your chrome version

**Comment by hendrikbgr** [comment]
fix in comment above
