### ISSUE TITLE
crash after proxy

### ISSUE THREAD

**Issue by 404-B** [hendrikbgr/ProtonMail-Account-Creator#33]
**Describe the bug**
script runs just fine, have webdriver installed in what i am assuming is the correct location but bugs out after connecting to proxy.. 
**To Reproduce**
crawl for proxy, x for auto, null for recovery

Traceback (most recent call last):
  File "emails.py", line 148, in <module>
    driver = webdriver.Chrome(executable_path='./driver/chromedriver', chrome_options=options)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

hardware/software
 - Ubuntu 64bit
 - Python 3 latest
 - Acer Swift laptop

**Additional context**
have tried as sudo, logged in as root in terminal, logged in as root from startup , have tried every which way... maybe something simple im getting wrong.

when installing chromedriver i used   " dpkg -i chromedriver.deb "
i installed requirements.txt with pip3 install -r
everythings up to date.. im confizzled

**Comment by hendrikbgr** [comment]
have you got the chromedrive located in the driver folder?

**Comment by 404-B** [comment]
when i cloned there was not a driver folder present in the dir, i created a folder "driver" and put it there?

driver folder is a little ambiguous , what is the proper location? or did i do correctly in creating a driver folder to put in b@404:~/ProtonMail-Account-Creator
b@404:~/ProtonMail-Account-Creator/driver
?
I also downloaded as a zip and no driver folder there either.
![Screenshot from 2021-04-13 01-56-19](https://user-images.githubusercontent.com/77077907/114526414-d0604a00-9bfb-11eb-9916-7380a2c86517.png)

there are quite a few driver folders.

**Comment by hendrikbgr** [comment]
yes creating the driver folder is still needed. But I will add it to the repo with the next update. I dont include the chromedriver because you need the matching chromedriver to your chrome version. Once you downloaded the linux chromedriver unzip it and place the 'chromedriver' file into the driver folder.

**Comment by hendrikbgr** [comment]
please reopen this issue if there are further issues
